export enum RouterList {
  HOME = '/',
  NOT_FOUND = '/*',
  SIGN_IN = '/sign-in',
  SIGN_UP = '/sign-up',
  FORUM = '/forum',
  FORUM_ID_PARAM = ':forumId',
  FORUM_TOPIC = '/forum/topic',
  TOPIC_ID_PARAM = ':topicId',
  GAME = '/game',
  LEADER_BOARD = '/leader-board',
  SERVER_ERROR = '/server-error',
  PROFILE = '/profile',
  PROFILE_ID_PARAM = ':id',
  PROFILE_EDIT = '/profile/edit',
}
